spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "[format_sql]": true
        "[show_sql]": true
    
  redis:
    port: 6379 
    host: localhost
    
logging:
  level:
    '[com.redis]': debug
    
jwt:
  header: Authorization
  secret: mynicknameislimjaewon
  